# Render Static Site Configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  command = "npm run build"
  publish = "build"

# Environment
[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://decentralized-booking-api.onrender.com"

# Headers for security and performance  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"